package lsi.sling.FragmentHandling;

import java.util.ArrayList;

/**
 * This class represents the clustered MS2Fragments generated by each PeakCluster
 */
public class MS2Cluster {

    private ArrayList<MS2Fragment> fragments;
    private double meanMZ;
    private double meanRT;

    /**
     * Creates an MS2Cluster with the input list of MS2Fragments. The intention is for the input list to be generated
     * by the DBScan clustering algorithm (in the PeakCluster class).
     * @param inputFragments The input list of MS2Fragments which all belong to the same cluster
     */
    public MS2Cluster(ArrayList<MS2Fragment> inputFragments){
        fragments = inputFragments;
        meanMZ = inputFragments.stream().mapToDouble(MS2Fragment::getMZ).summaryStatistics().getAverage();
        meanRT = inputFragments.stream().mapToDouble(MS2Fragment::getRT).summaryStatistics().getAverage();
    }

    public ArrayList<MS2Fragment> getFragments(){
        return fragments;
    }

    public double getMeanMZ(){
        return meanMZ;
    }

    public double getMeanRT(){
        return meanRT;
    }
}
